sonar.projectKey=anjo-traders
sonar.projectName=anjo-traders
sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**,**/static/**,**/media/**,**/*.min.js,**/dist/**,**/build/**,**/k8s/**,**/Dockerfile*,**/*.dockerfile
sonar.python.version=3
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml
