apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: anjo-traders/frontend
    newName: harbor.lab/anjo-traders/frontend
    newTag: main-f2f20182 # frontend
  - name: anjo-traders/backend
    newName: harbor.lab/anjo-traders/backend
    newTag: main-f2f20182 # backend
